// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfnvmozayuqyperiifsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmbnZtb3pheXVxeXBlcmlpZnN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTM3OTUsImV4cCI6MjA2NjU4OTc5NX0.BNkRSVYq9sXtPfOey5IHCLDSozKzaxxPDa_2HVFTcSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);